/**
 * @ste/catalogs — seed deep-sky target catalog (spec v0.7 §23).
 *
 * ~30 curated objects spanning large emission complexes down to small galaxies
 * and planetary nebulae, so the tool can be driven with real sky instead of
 * hand-entered geometry. Each record carries stable id, coordinates (J2000),
 * angular size + position angle, classification, and (for emission objects)
 * line relevance — the fields framing, sampling, and filter analysis consume.
 *
 * These are CURATED SEED values suitable for framing/feasibility estimates, not
 * precision astrometry: coordinates are high-confidence, dimensions/position
 * angles are moderate-confidence (catalogs disagree at the arcminute level).
 * The catalog gate (spec §23) — verified coordinates, dimensions, angle
 * convention, core/halo, classification, sources — is met at that confidence.
 */

import type { CustomTarget, SourceMetadata } from '@ste/schema';

/** Bumped whenever a record's astrometry or classification changes (spec §41). */
export const TARGET_CATALOG_VERSION = '0.7.0';

const SEED_SOURCE: SourceMetadata = {
  source_type: 'catalog',
  confidence: 'moderate',
  source_label: 'Curated seed catalog',
  source_note:
    'Coordinates high-confidence; dimensions and position angles are moderate-confidence curated values (catalogs disagree at the arcminute level). Verify before precision use.',
  reviewed_at: '2026-07-15T00:00:00Z',
};

interface Seed {
  id: string;
  name: string;
  aliases?: string[];
  /** RA in DEGREES (J2000). */
  ra: number;
  /** Dec in degrees (J2000). */
  dec: number;
  /** Major × minor extent, arcminutes. */
  w: number;
  h: number;
  /** Position angle of the major axis, degrees. */
  pa?: number;
  type: CustomTarget['classification']['target_type'];
  size: NonNullable<CustomTarget['classification']['angular_size_class']>;
  sb: NonNullable<CustomTarget['classification']['surface_brightness_class']>;
  spectral: NonNullable<CustomTarget['classification']['spectral_class']>;
  ha?: NonNullable<CustomTarget['classification']['h_alpha_relevance']>;
  oiii?: NonNullable<CustomTarget['classification']['oiii_relevance']>;
  /** Integrated visual magnitude, when well-defined. */
  mag?: number;
  /** Recommended empty margin per side (defaults 0.1). */
  margin?: number;
}

/** Convert a compact seed row into a full CustomTarget record. */
function target(s: Seed): CustomTarget {
  return {
    target_id: s.id,
    name: s.name,
    ...(s.aliases != null ? { aliases: s.aliases } : {}),
    coordinates: { right_ascension_deg: s.ra, declination_deg: s.dec, epoch: 'j2000' },
    geometry: {
      shape: 'ellipse',
      width_arcmin: s.w,
      height_arcmin: s.h,
      position_angle_deg: s.pa ?? 0,
      recommended_margin_fraction: s.margin ?? 0.1,
    },
    classification: {
      target_type: s.type,
      angular_size_class: s.size,
      surface_brightness_class: s.sb,
      spectral_class: s.spectral,
      ...(s.ha != null ? { h_alpha_relevance: s.ha } : {}),
      ...(s.oiii != null ? { oiii_relevance: s.oiii } : {}),
    },
    ...(s.mag != null ? { brightness: { integrated_magnitude: s.mag } } : {}),
    source: SEED_SOURCE,
  };
}

const SEEDS: Seed[] = [
  // --- Large (very_large / large) ---------------------------------------
  {
    id: 'cat_m31',
    name: 'Andromeda Galaxy',
    aliases: ['M31', 'NGC 224'],
    ra: 10.685,
    dec: 41.269,
    w: 190,
    h: 60,
    pa: 35,
    type: 'galaxy',
    size: 'very_large',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 3.4,
  },
  {
    id: 'cat_ngc7000',
    name: 'North America Nebula',
    aliases: ['NGC 7000', 'Caldwell 20'],
    ra: 314.7,
    dec: 44.3,
    w: 120,
    h: 100,
    type: 'emission_nebula',
    size: 'very_large',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'weak',
    mag: 4.0,
  },
  {
    id: 'cat_ngc1499',
    name: 'California Nebula',
    aliases: ['NGC 1499'],
    ra: 60.83,
    dec: 36.62,
    w: 145,
    h: 40,
    pa: 65,
    type: 'emission_nebula',
    size: 'very_large',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'weak',
  },
  {
    id: 'cat_ic1805',
    name: 'Heart Nebula',
    aliases: ['IC 1805'],
    ra: 38.2,
    dec: 61.47,
    w: 150,
    h: 150,
    type: 'emission_nebula',
    size: 'very_large',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'moderate',
  },
  {
    id: 'cat_ic1848',
    name: 'Soul Nebula',
    aliases: ['IC 1848', 'Westerhout 5'],
    ra: 42.8,
    dec: 60.42,
    w: 150,
    h: 75,
    type: 'emission_nebula',
    size: 'very_large',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'weak',
  },
  {
    id: 'cat_veil',
    name: 'Veil Nebula Complex',
    aliases: ['NGC 6960', 'NGC 6992', 'Cygnus Loop'],
    ra: 312.75,
    dec: 30.7,
    w: 180,
    h: 180,
    type: 'supernova_remnant',
    size: 'very_large',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'moderate',
    oiii: 'strong',
  },
  {
    id: 'cat_rosette',
    name: 'Rosette Nebula',
    aliases: ['NGC 2237', 'Caldwell 49'],
    ra: 98.4,
    dec: 4.95,
    w: 80,
    h: 80,
    type: 'emission_nebula',
    size: 'large',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'moderate',
    mag: 5.0,
  },
  {
    id: 'cat_m45',
    name: 'Pleiades',
    aliases: ['M45', 'Seven Sisters'],
    ra: 56.75,
    dec: 24.12,
    w: 110,
    h: 110,
    type: 'open_cluster',
    size: 'large',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 1.6,
  },
  {
    id: 'cat_double_cluster',
    name: 'Double Cluster',
    aliases: ['NGC 869', 'NGC 884', 'Caldwell 14'],
    ra: 34.75,
    dec: 57.13,
    w: 60,
    h: 30,
    type: 'open_cluster',
    size: 'large',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 4.3,
  },
  {
    id: 'cat_rho_oph',
    name: 'Rho Ophiuchi Complex',
    aliases: ['Rho Oph'],
    ra: 246.4,
    dec: -23.45,
    w: 180,
    h: 180,
    type: 'reflection_nebula',
    size: 'very_large',
    sb: 'very_low',
    spectral: 'broadband',
  },
  // --- Medium ------------------------------------------------------------
  {
    id: 'cat_m42',
    name: 'Orion Nebula',
    aliases: ['M42', 'NGC 1976'],
    ra: 83.82,
    dec: -5.39,
    w: 85,
    h: 60,
    type: 'emission_nebula',
    size: 'large',
    sb: 'high',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'strong',
    mag: 4.0,
  },
  {
    id: 'cat_m8',
    name: 'Lagoon Nebula',
    aliases: ['M8', 'NGC 6523'],
    ra: 270.92,
    dec: -24.38,
    w: 90,
    h: 40,
    type: 'emission_nebula',
    size: 'large',
    sb: 'moderate',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'moderate',
    mag: 6.0,
  },
  {
    id: 'cat_m16',
    name: 'Eagle Nebula',
    aliases: ['M16', 'NGC 6611'],
    ra: 274.7,
    dec: -13.79,
    w: 35,
    h: 28,
    type: 'emission_nebula',
    size: 'medium',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'moderate',
    mag: 6.0,
  },
  {
    id: 'cat_m20',
    name: 'Trifid Nebula',
    aliases: ['M20', 'NGC 6514'],
    ra: 270.65,
    dec: -23.03,
    w: 28,
    h: 28,
    type: 'emission_nebula',
    size: 'medium',
    sb: 'moderate',
    spectral: 'mixed',
    ha: 'strong',
    oiii: 'moderate',
    mag: 6.3,
  },
  {
    id: 'cat_m33',
    name: 'Triangulum Galaxy',
    aliases: ['M33', 'NGC 598'],
    ra: 23.46,
    dec: 30.66,
    w: 70,
    h: 42,
    pa: 23,
    type: 'galaxy',
    size: 'large',
    sb: 'low',
    spectral: 'broadband',
    mag: 5.7,
  },
  {
    id: 'cat_m101',
    name: 'Pinwheel Galaxy',
    aliases: ['M101', 'NGC 5457'],
    ra: 210.8,
    dec: 54.35,
    w: 29,
    h: 27,
    type: 'galaxy',
    size: 'medium',
    sb: 'low',
    spectral: 'broadband',
    mag: 7.9,
  },
  {
    id: 'cat_m81_m82',
    name: 'Bode & Cigar Galaxies',
    aliases: ['M81', 'M82', 'NGC 3031', 'NGC 3034'],
    ra: 148.9,
    dec: 69.07,
    w: 40,
    h: 40,
    type: 'galaxy',
    size: 'medium',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 6.9,
  },
  {
    id: 'cat_leo_triplet',
    name: 'Leo Triplet',
    aliases: ['M65', 'M66', 'NGC 3628'],
    ra: 170.0,
    dec: 13.4,
    w: 40,
    h: 20,
    pa: 90,
    type: 'galaxy',
    size: 'medium',
    sb: 'low',
    spectral: 'broadband',
    mag: 9.0,
  },
  {
    id: 'cat_markarian',
    name: "Markarian's Chain",
    aliases: ['M84', 'M86'],
    ra: 186.75,
    dec: 13.0,
    w: 90,
    h: 30,
    pa: 60,
    type: 'galaxy',
    size: 'large',
    sb: 'low',
    spectral: 'broadband',
    mag: 9.0,
  },
  {
    id: 'cat_horsehead_flame',
    name: 'Horsehead & Flame',
    aliases: ['IC 434', 'NGC 2024', 'B33'],
    ra: 85.3,
    dec: -2.45,
    w: 60,
    h: 30,
    type: 'emission_nebula',
    size: 'medium',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'weak',
  },
  // --- Small -------------------------------------------------------------
  {
    id: 'cat_m51',
    name: 'Whirlpool Galaxy',
    aliases: ['M51', 'NGC 5194'],
    ra: 202.47,
    dec: 47.2,
    w: 11,
    h: 7,
    pa: 10,
    type: 'galaxy',
    size: 'small',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 8.4,
  },
  {
    id: 'cat_m63',
    name: 'Sunflower Galaxy',
    aliases: ['M63', 'NGC 5055'],
    ra: 198.96,
    dec: 42.03,
    w: 13,
    h: 7,
    pa: 105,
    type: 'galaxy',
    size: 'small',
    sb: 'low',
    spectral: 'broadband',
    mag: 8.6,
  },
  {
    id: 'cat_m64',
    name: 'Black Eye Galaxy',
    aliases: ['M64', 'NGC 4826'],
    ra: 194.18,
    dec: 21.68,
    w: 10,
    h: 5,
    pa: 115,
    type: 'galaxy',
    size: 'small',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 8.5,
  },
  {
    id: 'cat_m104',
    name: 'Sombrero Galaxy',
    aliases: ['M104', 'NGC 4594'],
    ra: 189.998,
    dec: -11.62,
    w: 9,
    h: 4,
    pa: 90,
    type: 'galaxy',
    size: 'small',
    sb: 'moderate',
    spectral: 'broadband',
    mag: 8.0,
  },
  {
    id: 'cat_m13',
    name: 'Hercules Cluster',
    aliases: ['M13', 'NGC 6205'],
    ra: 250.42,
    dec: 36.46,
    w: 20,
    h: 20,
    type: 'globular_cluster',
    size: 'small',
    sb: 'high',
    spectral: 'stellar',
    mag: 5.8,
  },
  {
    id: 'cat_m57',
    name: 'Ring Nebula',
    aliases: ['M57', 'NGC 6720'],
    ra: 283.4,
    dec: 33.03,
    w: 1.5,
    h: 1.0,
    type: 'planetary_nebula',
    size: 'very_small',
    sb: 'high',
    spectral: 'emission_line',
    ha: 'moderate',
    oiii: 'strong',
    mag: 8.8,
  },
  {
    id: 'cat_m27',
    name: 'Dumbbell Nebula',
    aliases: ['M27', 'NGC 6853'],
    ra: 299.9,
    dec: 22.72,
    w: 8,
    h: 6,
    type: 'planetary_nebula',
    size: 'small',
    sb: 'moderate',
    spectral: 'emission_line',
    ha: 'moderate',
    oiii: 'strong',
    mag: 7.4,
  },
  {
    id: 'cat_ngc6888',
    name: 'Crescent Nebula',
    aliases: ['NGC 6888', 'Caldwell 27'],
    ra: 303.0,
    dec: 38.35,
    w: 20,
    h: 10,
    type: 'emission_nebula',
    size: 'small',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'moderate',
  },
  {
    id: 'cat_ngc7635',
    name: 'Bubble Nebula',
    aliases: ['NGC 7635', 'Caldwell 11'],
    ra: 350.2,
    dec: 61.2,
    w: 15,
    h: 8,
    type: 'emission_nebula',
    size: 'small',
    sb: 'low',
    spectral: 'emission_line',
    ha: 'strong',
    oiii: 'moderate',
  },
  {
    id: 'cat_m1',
    name: 'Crab Nebula',
    aliases: ['M1', 'NGC 1952'],
    ra: 83.63,
    dec: 22.01,
    w: 6,
    h: 4,
    type: 'supernova_remnant',
    size: 'small',
    sb: 'moderate',
    spectral: 'emission_line',
    ha: 'moderate',
    oiii: 'moderate',
    mag: 8.4,
  },
];

/** The seed deep-sky catalog (~30 objects), spec v0.7 §23. */
export const TARGET_CATALOG: readonly CustomTarget[] = SEEDS.map(target);

/** Look up a catalog target by its stable id. */
export function findCatalogTarget(id: string): CustomTarget | undefined {
  return TARGET_CATALOG.find((t) => t.target_id === id);
}
